### ISSUE TITLE
Choose the ip address

### ISSUE THREAD

**Issue by GuilhermeLuan** [Stremio/server-docker#10] opened 2023-06-08 16:12 UTC
It should provide an option to select the IP address. Currently, I am unable to use the Docker server on my mobile phone because the IP address is set to my local machine's address, which is 127.0.0.1. Moreover, I require the streaming endpoint to support HTTPS.

**Comment by jaruba** [comment] 2023-06-09 07:17
Duplicate of: https://github.com/Stremio/server-docker/issues/8

Stremio only provides SSL certificates for LAN use, exposing the server to the worldwide web is not officially supported.

**Closed by jaruba** 2023-06-09 07:17 UTC

**Comment by GuilhermeLuan** [comment] 2023-06-09 12:52
I don't want to expose the server to the entire world. I want to use it at home. Additionally, it is not working on my cellphone without HTTPS. I tried running the Stremio service on my Windows machine and it works fine, but it doesn't perform well on my Linux server.

**Comment by GuilhermeLuan** [comment] 2023-06-09 15:24
![image](https://github.com/Stremio/server-docker/assets/32211071/769c4063-ae24-4726-8af2-e33b6e9293fe)
For a more detailed explanation, I need the Streaming HTTPS endpoint with the my machine ip 192.168.1.21.

**Comment by jaruba** [comment] 2023-06-09 15:47
And you can't select the 192.168.1.21 IP from the "Enable remote HTTPS connections" options? (from your screenshot)

**Comment by GuilhermeLuan** [comment] 2023-06-09 15:56
I can't. The  Stremio server is running on my home server.

**Comment by jaruba** [comment] 2023-06-09 16:05
> Additionally, it is not working on my cellphone without HTTPS

It's not meant to, for security reasons in can only run on the same device (through `localhost`) without HTTPS

> I can't. The Stremio server is running on my home server.

Then it only has access to the docker virtual network, which is why it can't see your LAN IP, this is expected, and the issue is still a duplicate of #8 

You cannot enable HTTPS for your local network at this point because the server is caged in a virtual network, (docker's) you will be able once #8 is solved.

**Comment by GuilhermeLuan** [comment] 2023-06-09 16:33
ok! Thanks for the help!

**Comment by aicynide** [comment] 2023-07-18 05:43
> Duplicate of: #8
> 
> Stremio only provides SSL certificates for LAN use, exposing the server to the worldwide web is not officially supported.

I can't use wireguard all day
