### ISSUE TITLE
Failed to fetch error

### ISSUE THREAD

**Issue by Erkko68** [Stremio/server-docker#14] opened 2023-07-22 15:21 UTC
I'm running the server-docker container on my home server based on Debian, and I'm using portainer. I can access stremio using the machine's IP address and the stremio port (http://192.168.0.245:11470/). But when I try to play any media, it gives me the error "Failed to fetch". 

![Screenshot_2](https://github.com/Stremio/server-docker/assets/47712373/b1303c2e-81bc-440b-b404-bb0aafad984d)

In settings, in the Streaming section, it says that it can't reach the server, which has the same URL address. I've tried changing the URL to 127.0.0.01:11470 and 12470, but nothing works.

I've tried following the previous closed issue [#3](https://github.com/Stremio/server-docker/issues/3)  since it might be a connection problem where the container is not accessing my local network, but I still can't figure out how to make it work.

Thanks in advance.
![Screenshot_1](https://github.com/Stremio/server-docker/assets/47712373/31bd891b-310d-481c-b6ac-02e44748f0bc)

**Comment by jaruba** [comment] 2023-07-22 16:37
This issue is a duplicate of https://github.com/Stremio/server-docker/issues/8

**Closed** 2023-07-23 08:35 UTC
